module.exports = {
    userModel: require("./user.js"),
    userInfoModel: require("./user-info.js"),
    userAvatarsModel: require("./user-avatars.js"),
    companiesModel: require("./companies.js"),
    addressesModel: require("./addresses.js"),
    userSettingsModel: require("./user-settings.js"),
    userPreferencesModel: require("./user-preferences.js"),
    projectsModel: require("./projects.js"),
    documentsModel: require("./documents.js"),
    templatesModel: require("./templates.js"),
    templatesHistoryModel: require("./templates-history.js"),
    templatesSnapshotModel: require("./templates-snapshot.js"),
    templatesLeverageModel: require("./templates-leverage.js"),
    templatesPEFundModel: require("./templates-PE-fund.js"),
    templatesPDFundModel: require("./templates-PD-fund.js"),
    templatesFoFFundModel: require("./templates-FoF-fund.js"),
    templatesRealFundModel: require("./templates-Real-fund.js"),
    currencyRatesModel: require("./currency-rates.js"),
    analyticsModel: require("./analytics.js"),
    sizeRangesModel: require("./size-ranges.js"),
    leverageRangesModel: require("./leverage-ranges.js"),
};
