;
module.exports = {
    users: require("./user-management.js"),
    userInfo: require("./user-info.js"),
    addresses: require("./addresses.js"),
    companies: require("./companies.js"),
    userSettings: require("./user-settings.js"),
    userPreferences: require("./user-preferences.js"),
    userAvatars: require("./user-avatars.js"),
    currencyRates: require("./currency-rates.js"),
    documents: require("./documents.js"),
    projects: require("./projects.js"),
    templates: require("./templates.js"),
    templatesSnapshot: require("./templates-snapshot.js"),
    templatesHistory: require("./templates-history.js"),
    templatesLeverage: require("./templates-leverage.js"),
    analytics: require("./analytics.js"),
    templatesPEFund: require("./templates-PE-fund.js"),
    templatesPDFund: require("./templates-PD-fund.js"),
    templatesFoFFund: require("./templates-FoF-fund.js"),
    templatesRealFund: require("./templates-Real-fund.js"),
    sizeRanges: require("./size-ranges.js"),
    leverageRanges: require("./leverage-ranges.js"),
}